name: Daily Database Cleanup

on:
  schedule:
    # Her gece Türkiye saatiyle 00:00'da çalışır (UTC 21:00)
    - cron: '0 21 * * *'
  workflow_dispatch: # İstediğinde GitHub panelinden elle de çalıştırabilmen için

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Firebase Messages
        run: |
          curl -X DELETE "https://message-site-329ee-default-rtdb.firebaseio.com/messages.json?auth=${{ secrets.FIREBASE_SECRET }}"
